services:
  - type: web
    name: bitki-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "10000"
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_ACCESS_CODE
        value: "BITKI_ADMIN_2024"
      - key: BASE_URL
        value: "https://bitki-backend.onrender.com"
    disk:
      name: uploads
      mountPath: /opt/render/project/uploads
      sizeGB: 1

disks:
  - name: uploads
    sizeGB: 1